# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
#- tag
- archive
- recent_posts

# Miscellaneous
google_analytics: false
baidu_analytics: true
favicon: ./favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: